#!/usr/bin/env python3
"""Generate the runtime charm catalog from authoring + processing data.

    python3 Design/Aurie3D/Scripts/generate_charm_catalog.py [--check]

Merges TWO sources into `Auries/Models/CharmCatalog.generated.swift`:

  * `AurieCharmLibrary/_MANIFESTS/charm_taxonomy.json` — HAND-AUTHORED
    product truth: category/placement/acquisition catalogs, per-charm
    editorial metadata, Birth-Charm triggers. The charm processor never
    writes it.
  * `AurieCharmLibrary/_MANIFESTS/charms.json` — PROCESSING output.
    Used only to cross-check that authored charms exist (a warning, not
    an error: the taxonomy may run ahead of assets or outlive removed
    ones) and to inherit a displayName when the author omits one.

Editorial metadata therefore survives every processor re-run, and the
runtime catalog is data all the way down — no hand-grown Swift tables.

VALIDATION (hard errors — the file is product data, typos must not
reach the app): every category / placement / acquisition-source id a
charm references must exist in its catalog; every birthTriggerIDs entry
must reference a defined trigger AND that trigger must point back at
the same charm; every trigger's unlockCharmID must be an authored charm.
"""
import argparse
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
REPO = HERE.parents[2]
TAXONOMY = REPO / "AurieCharmLibrary/_MANIFESTS/charm_taxonomy.json"
MANIFEST = REPO / "AurieCharmLibrary/_MANIFESTS/charms.json"
OUTPUT = REPO / "Auries/Models/CharmCatalog.generated.swift"


def load():
    tax = json.loads(TAXONOMY.read_text())
    man = json.loads(MANIFEST.read_text())
    return tax, {c["id"]: c for c in man["charms"]}


def validate(tax, library):
    errors, warnings = [], []
    cat_ids = {c["id"] for c in tax["categories"]}
    place_ids = {p["id"] for p in tax["placements"]}
    src_ids = {s["id"] for s in tax["acquisitionSources"]}
    triggers = {t["id"]: t for t in tax.get("birthTriggers", [])}
    charms = tax["charms"]

    for cid, c in charms.items():
        for cat in c.get("categories", []):
            if cat not in cat_ids:
                errors.append(f"{cid}: unknown category '{cat}'")
        for p in c.get("placements", []):
            if p not in place_ids:
                errors.append(f"{cid}: unknown placement '{p}'")
        for s in c.get("acquisitionSources", []):
            if s not in src_ids:
                errors.append(f"{cid}: unknown acquisitionSource '{s}'")
        for t in c.get("birthTriggerIDs", []):
            if t not in triggers:
                errors.append(f"{cid}: unknown birthTrigger '{t}'")
            elif triggers[t]["unlockCharmID"] != cid:
                errors.append(
                    f"{cid}: trigger '{t}' unlocks "
                    f"'{triggers[t]['unlockCharmID']}', not this charm")
        if not c.get("placements"):
            errors.append(f"{cid}: no placements authored")
        if cid not in library:
            warnings.append(f"{cid}: not in charms.json (asset pending "
                            "or removed — allowed)")
    for t in triggers.values():
        if t["unlockCharmID"] not in charms:
            errors.append(f"trigger {t['id']}: unlockCharmID "
                          f"'{t['unlockCharmID']}' is not an authored charm")
    return errors, warnings


def swift_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def swift_arr(xs):
    return "[" + ", ".join(swift_str(x) for x in xs) + "]"


def emit(tax, library):
    lines = [
        "// CharmCatalog.generated.swift",
        "// GENERATED by Design/Aurie3D/Scripts/generate_charm_catalog.py",
        "// from AurieCharmLibrary/_MANIFESTS/charm_taxonomy.json (editorial)",
        "// merged with _MANIFESTS/charms.json (processing).",
        "// DO NOT EDIT BY HAND — edit the taxonomy and re-run the generator.",
        "",
        "import Foundation",
        "",
        "enum GeneratedCharmCatalog {",
        "    static let categoryDisplayNames: [String: String] = [",
    ]
    for c in tax["categories"]:
        lines.append(f"        {swift_str(c['id'])}: "
                     f"{swift_str(c['displayName'])},")
    lines += ["    ]", "",
              "    static let placementDisplayNames: [String: String] = ["]
    for p in tax["placements"]:
        lines.append(f"        {swift_str(p['id'])}: "
                     f"{swift_str(p['displayName'])},")
    lines += ["    ]", "",
              "    static let acquisitionSourceDisplayNames: [String: String] = ["]
    for s in tax["acquisitionSources"]:
        lines.append(f"        {swift_str(s['id'])}: "
                     f"{swift_str(s['displayName'])},")
    lines += ["    ]", "",
              "    static let birthTriggers: [BirthCharmTrigger] = ["]
    for t in tax.get("birthTriggers", []):
        lines.append(
            "        BirthCharmTrigger("
            f"id: {swift_str(t['id'])}, "
            f"acceptedRecognitionLabels: {swift_arr(t['acceptedRecognitionLabels'])}, "
            f"unlockCharmID: {swift_str(t['unlockCharmID'])}),")
    lines += ["    ]", "",
              "    static let definitions: [CharmDefinition] = ["]
    for cid in sorted(tax["charms"]):
        c = tax["charms"][cid]
        name = c.get("displayName") \
            or library.get(cid, {}).get("displayName", cid)
        lines.append(
            "        CharmDefinition("
            f"id: {swift_str(cid)}, "
            f"displayName: {swift_str(name)}, "
            f"categories: {swift_arr(c.get('categories', []))}, "
            f"placements: {swift_arr(c.get('placements', []))}, "
            f"acquisitionSources: {swift_arr(c.get('acquisitionSources', []))}, "
            f"birthTriggerIDs: {swift_arr(c.get('birthTriggerIDs', []))}, "
            f"launch: {'true' if c.get('launch', False) else 'false'}),")
    lines += ["    ]", "}", ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="validate only; do not write")
    args = ap.parse_args()
    tax, library = load()
    errors, warnings = validate(tax, library)
    for w in warnings:
        print(f"WARN  {w}")
    if errors:
        for e in errors:
            print(f"ERROR {e}", file=sys.stderr)
        sys.exit(1)
    n = (len(tax['charms']), len(tax['categories']),
         len(tax.get('birthTriggers', [])))
    if args.check:
        print(f"OK — {n[0]} charms, {n[1]} categories, {n[2]} triggers")
        return
    OUTPUT.write_text(emit(tax, library))
    print(f"wrote {OUTPUT.relative_to(REPO)} — "
          f"{n[0]} charms, {n[1]} categories, {n[2]} triggers")


if __name__ == "__main__":
    main()
